### ISSUE TITLE
UpdateStateByGpsPosition 中state->cov的计算公式

### ISSUE THREAD

**Issue by kelebujiabing** [ydsf16/imu_gps_localization#6]
楼主好，感谢分享。有个疑问请教，在UpdateStateByGpsPosition函数中，state->cov的计算是不是应该用更新部分的公式P=（I-KH)P，而不是预测部分的公式 P=Fx P FxT + Fi Q FiT ？

**Comment by ramdonPerson** [comment]
不是的，这是卡尔曼滤波器的概念，计算kalman gain时使用的就是预测部份propagation下来的协方差矩阵。

**Comment by HuangZhen66** [comment]
P=（I-KH)P是协方差更新的最简单的形式，作者用的是P=（I-KH)P(I-KHT) + KVKT，这种形式更稳定。详细可以看下[这个博客](https://blog.csdn.net/sunqin_csdn/article/details/108903580)
![企业微信截图_16581133954018](https://user-images.githubusercontent.com/84693413/179439427-4e32bd04-1af0-4f93-a3ff-827fad5d1966.png)

**Comment by kelebujiabing** [comment]
谢谢
